// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orcamento.InfraStructure.Data.Context;

#nullable disable

namespace Orcamento.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Orcamento.Models.OrcamentoGeral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OrcamentoGeral");
                });

            modelBuilder.Entity("Orcamento.Models.OrcamentoP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionCreate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FormaPag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrcamentoGeralId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrcamentoPId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoGeralId");

                    b.HasIndex("OrcamentoPId");

                    b.ToTable("OrcamentoP");
                });

            modelBuilder.Entity("Orcamento.Models.OrcamentoRec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActionCreateR")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrcamentoGeralId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrcamentoRecId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ValueR")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoGeralId");

                    b.HasIndex("OrcamentoRecId");

                    b.ToTable("OrcamentoRec");
                });

            modelBuilder.Entity("Orcamento.Models.OrcamentoP", b =>
                {
                    b.HasOne("Orcamento.Models.OrcamentoGeral", null)
                        .WithMany("Gastos")
                        .HasForeignKey("OrcamentoGeralId");

                    b.HasOne("Orcamento.Models.OrcamentoP", null)
                        .WithMany("Gastos")
                        .HasForeignKey("OrcamentoPId");
                });

            modelBuilder.Entity("Orcamento.Models.OrcamentoRec", b =>
                {
                    b.HasOne("Orcamento.Models.OrcamentoGeral", null)
                        .WithMany("Receitas")
                        .HasForeignKey("OrcamentoGeralId");

                    b.HasOne("Orcamento.Models.OrcamentoRec", null)
                        .WithMany("Receita")
                        .HasForeignKey("OrcamentoRecId");
                });

            modelBuilder.Entity("Orcamento.Models.OrcamentoGeral", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("Orcamento.Models.OrcamentoP", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Orcamento.Models.OrcamentoRec", b =>
                {
                    b.Navigation("Receita");
                });
#pragma warning restore 612, 618
        }
    }
}
